// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VPointCare.Web.Data;

#nullable disable

namespace VPointCare.Web.Migrations
{
    [DbContext(typeof(VPointCareDbContext))]
    [Migration("20260505020710_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MAiProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("ApiKeyTerenkripsi")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("ApiKeyTerenkripsi");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("BaseUrl");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("KodeProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KodeProvider");

                    b.Property<string>("ModelDefault")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModelDefault");

                    b.Property<string>("NamaProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NamaProvider");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.HasKey("Id");

                    b.ToTable("MAiProvider", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MAnggotaGrupWhatsapp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid?>("IdCustomer")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCustomer");

                    b.Property<Guid>("IdGrupWhatsapp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdGrupWhatsapp");

                    b.Property<Guid>("IdNomorWhatsapp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdNomorWhatsapp");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<string>("PeranAnggota")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PeranAnggota");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.HasKey("Id");

                    b.ToTable("MAnggotaGrupWhatsapp", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Catatan")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Catatan");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("IdExternal")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("IdExternal");

                    b.Property<Guid?>("IdInstansi")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdInstansi");

                    b.Property<string>("Jabatan")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Jabatan");

                    b.Property<string>("KodeCustomer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KodeCustomer");

                    b.Property<string>("NamaCustomer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NamaCustomer");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<string>("SumberData")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SumberData");

                    b.Property<string>("Telepon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Telepon");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<DateTime?>("TglSinkronTerakhir")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglSinkronTerakhir");

                    b.HasKey("Id");

                    b.ToTable("MCustomer", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MEndpointIntegrasi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("HeaderJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HeaderJson");

                    b.Property<string>("KodeEndpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("KodeEndpoint");

                    b.Property<string>("MetodeHttp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MetodeHttp");

                    b.Property<string>("NamaEndpoint")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NamaEndpoint");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<string>("UrlEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("UrlEndpoint");

                    b.HasKey("Id");

                    b.ToTable("MEndpointIntegrasi", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MGrupWhatsapp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Deskripsi")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Deskripsi");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("IdExternal")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("IdExternal");

                    b.Property<string>("IdGrupWaha")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("IdGrupWaha");

                    b.Property<Guid>("IdInstansi")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdInstansi");

                    b.Property<string>("KodeGrup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KodeGrup");

                    b.Property<string>("NamaGrup")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NamaGrup");

                    b.Property<string>("NomorGrupWhatsapp")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NomorGrupWhatsapp");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<string>("SumberData")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SumberData");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.HasKey("Id");

                    b.ToTable("MGrupWhatsapp", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MHakAkses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Keterangan");

                    b.Property<string>("KodeHakAkses")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("KodeHakAkses");

                    b.Property<string>("Modul")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Modul");

                    b.Property<string>("NamaHakAkses")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NamaHakAkses");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.HasKey("Id");

                    b.ToTable("MHakAkses", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MHariLibur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("BerlakuTahunan")
                        .HasColumnType("bit")
                        .HasColumnName("BerlakuTahunan");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Keterangan");

                    b.Property<string>("NamaHariLibur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NamaHariLibur");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<DateTime>("TanggalLibur")
                        .HasColumnType("datetime2")
                        .HasColumnName("TanggalLibur");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.HasKey("Id");

                    b.ToTable("MHariLibur", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MInstansi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Alamat")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Alamat");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("IdExternal")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("IdExternal");

                    b.Property<string>("KodeInstansi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KodeInstansi");

                    b.Property<string>("KodePos")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("KodePos");

                    b.Property<string>("Kota")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Kota");

                    b.Property<string>("NamaInstansi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NamaInstansi");

                    b.Property<string>("Negara")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Negara");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<string>("Provinsi")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Provinsi");

                    b.Property<string>("SumberData")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SumberData");

                    b.Property<string>("Telepon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Telepon");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<DateTime?>("TglSinkronTerakhir")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglSinkronTerakhir");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Website");

                    b.HasKey("Id");

                    b.ToTable("MInstansi", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MKategoriTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Keterangan");

                    b.Property<string>("KodeKategori")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KodeKategori");

                    b.Property<string>("NamaKategori")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NamaKategori");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.HasKey("Id");

                    b.ToTable("MKategoriTicket", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MNomorWhatsapp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid?>("IdCustomer")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCustomer");

                    b.Property<string>("IdExternal")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("IdExternal");

                    b.Property<Guid?>("IdInstansi")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdInstansi");

                    b.Property<string>("JabatanKontak")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("JabatanKontak");

                    b.Property<string>("NamaKontak")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NamaKontak");

                    b.Property<bool>("NomorUtama")
                        .HasColumnType("bit")
                        .HasColumnName("NomorUtama");

                    b.Property<string>("NomorWhatsapp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("NomorWhatsapp");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<string>("SumberData")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SumberData");

                    b.Property<bool>("Terverifikasi")
                        .HasColumnType("bit")
                        .HasColumnName("Terverifikasi");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.HasKey("Id");

                    b.ToTable("MNomorWhatsapp", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MPengaturanAi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("ApiKeyTerenkripsi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ApiKeyTerenkripsi");

                    b.Property<bool>("AutoReplyAktif")
                        .HasColumnType("bit")
                        .HasColumnName("AutoReplyAktif");

                    b.Property<bool>("AutoReplyDiluarJamKerja")
                        .HasColumnType("bit")
                        .HasColumnName("AutoReplyDiluarJamKerja");

                    b.Property<bool>("AutoReplyHariLibur")
                        .HasColumnType("bit")
                        .HasColumnName("AutoReplyHariLibur");

                    b.Property<bool>("AutoReplyJamKerjaBerlanjut")
                        .HasColumnType("bit")
                        .HasColumnName("AutoReplyJamKerjaBerlanjut");

                    b.Property<bool>("AutoReplyJamKerjaSapaan")
                        .HasColumnType("bit")
                        .HasColumnName("AutoReplyJamKerjaSapaan");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("BaseUrl");

                    b.Property<int>("BatasRiwayatPesan")
                        .HasColumnType("int")
                        .HasColumnName("BatasRiwayatPesan");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("HariKerja")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HariKerja");

                    b.Property<TimeSpan>("JamKerjaMulai")
                        .HasColumnType("time(0)")
                        .HasColumnName("JamKerjaMulai");

                    b.Property<TimeSpan>("JamKerjaSelesai")
                        .HasColumnType("time(0)")
                        .HasColumnName("JamKerjaSelesai");

                    b.Property<int>("JedaNotifikasiMenit")
                        .HasColumnType("int")
                        .HasColumnName("JedaNotifikasiMenit");

                    b.Property<bool>("KirimKeWaha")
                        .HasColumnType("bit")
                        .HasColumnName("KirimKeWaha");

                    b.Property<string>("KodePengaturan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KodePengaturan");

                    b.Property<string>("KodePeranPenerimaNotifikasi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("KodePeranPenerimaNotifikasi");

                    b.Property<int>("MenitTungguNotifikasi")
                        .HasColumnType("int")
                        .HasColumnName("MenitTungguNotifikasi");

                    b.Property<string>("ModeKirim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModeKirim");

                    b.Property<string>("ModelAi")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModelAi");

                    b.Property<string>("NamaPengaturan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NamaPengaturan");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<bool>("NotifikasiChatBelumTerbalasAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NotifikasiChatBelumTerbalasAktif");

                    b.Property<string>("PromptSistem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PromptSistem");

                    b.Property<string>("ProviderAi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ProviderAi");

                    b.Property<string>("TemplateDiluarJamKerja")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TemplateDiluarJamKerja");

                    b.Property<string>("TemplateFallback")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TemplateFallback");

                    b.Property<string>("TemplateHariLibur")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TemplateHariLibur");

                    b.Property<string>("TemplateJamKerjaSapaan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TemplateJamKerjaSapaan");

                    b.Property<string>("TemplateNotifikasiChatBelumTerbalas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TemplateNotifikasiChatBelumTerbalas");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<string>("ZonaWaktu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ZonaWaktu");

                    b.HasKey("Id");

                    b.ToTable("MPengaturanAi", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MPengetahuan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("IsiPengetahuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IsiPengetahuan");

                    b.Property<string>("JudulPengetahuan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("JudulPengetahuan");

                    b.Property<string>("KodePengetahuan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KodePengetahuan");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<string>("Tag")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Tag");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.HasKey("Id");

                    b.ToTable("MPengetahuan", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MPengguna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Email");

                    b.Property<DateTime?>("EmailTerverifikasiPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("EmailTerverifikasiPada");

                    b.Property<string>("FotoProfilPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FotoProfilPath");

                    b.Property<Guid>("IdPeran")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdPeran");

                    b.Property<string>("Jabatan")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Jabatan");

                    b.Property<DateTime?>("LoginTerakhirPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("LoginTerakhirPada");

                    b.Property<string>("NamaPengguna")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NamaPengguna");

                    b.Property<string>("NomorWhatsappInternal")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("NomorWhatsappInternal");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Password");

                    b.Property<string>("RememberToken")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RememberToken");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("MPengguna", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MPeran", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Keterangan");

                    b.Property<string>("KodePeran")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KodePeran");

                    b.Property<string>("NamaPeran")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NamaPeran");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.HasKey("Id");

                    b.ToTable("MPeran", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MPeranHakAkses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid>("IdHakAkses")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdHakAkses");

                    b.Property<Guid>("IdPeran")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdPeran");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.HasKey("Id");

                    b.ToTable("MPeranHakAkses", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MPrioritasTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int?>("BatasSlaMenit")
                        .HasColumnType("int")
                        .HasColumnName("BatasSlaMenit");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("KodePrioritas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KodePrioritas");

                    b.Property<string>("NamaPrioritas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NamaPrioritas");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<int>("Urutan")
                        .HasColumnType("int")
                        .HasColumnName("Urutan");

                    b.Property<string>("Warna")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Warna");

                    b.HasKey("Id");

                    b.ToTable("MPrioritasTicket", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MProdukCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid?>("IdCustomer")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCustomer");

                    b.Property<Guid?>("IdInstansi")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdInstansi");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Keterangan");

                    b.Property<string>("KodeProduk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KodeProduk");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NamaProduk");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<DateTime?>("TglBerakhir")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBerakhir");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<DateTime?>("TglMulai")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglMulai");

                    b.HasKey("Id");

                    b.ToTable("MProdukCustomer", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MSesiWhatsapp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ApiKey");

                    b.Property<string>("BaseUrlWaha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("BaseUrlWaha");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("KodeSesi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KodeSesi");

                    b.Property<string>("NamaSesi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NamaSesi");

                    b.Property<string>("NomorTerhubung")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("NomorTerhubung");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<string>("StatusSesi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("StatusSesi");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<string>("WebhookToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("WebhookToken");

                    b.HasKey("Id");

                    b.HasIndex("KodeSesi")
                        .IsUnique();

                    b.ToTable("MSesiWhatsapp", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MStatusChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("KodeStatusChat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KodeStatusChat");

                    b.Property<string>("NamaStatusChat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NamaStatusChat");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<int>("Urutan")
                        .HasColumnType("int")
                        .HasColumnName("Urutan");

                    b.Property<string>("Warna")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Warna");

                    b.HasKey("Id");

                    b.ToTable("MStatusChat", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MStatusTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("KodeStatusTicket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KodeStatusTicket");

                    b.Property<string>("NamaStatusTicket")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NamaStatusTicket");

                    b.Property<bool>("NonAktif")
                        .HasColumnType("bit")
                        .HasColumnName("NonAktif");

                    b.Property<bool>("StatusFinal")
                        .HasColumnType("bit")
                        .HasColumnName("StatusFinal");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<int>("Urutan")
                        .HasColumnType("int")
                        .HasColumnName("Urutan");

                    b.Property<string>("Warna")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Warna");

                    b.HasKey("Id");

                    b.ToTable("MStatusTicket", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.MUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<DateTime?>("BlockedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("blocked_at");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("RememberToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("remember_token");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("MUser", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TAiPermintaan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid?>("IdAiProvider")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdAiProvider");

                    b.Property<Guid?>("IdChatM")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdChatM");

                    b.Property<Guid?>("IdTicketM")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdTicketM");

                    b.Property<string>("JenisPermintaan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("JenisPermintaan");

                    b.Property<string>("ModelAi")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModelAi");

                    b.Property<string>("PesanError")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PesanError");

                    b.Property<string>("PromptJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PromptJson");

                    b.Property<string>("PromptRingkas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PromptRingkas");

                    b.Property<string>("ProviderAi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ProviderAi");

                    b.Property<string>("StatusPermintaan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("StatusPermintaan");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<DateTime?>("TglMulai")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglMulai");

                    b.Property<DateTime?>("TglSelesai")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglSelesai");

                    b.HasKey("Id");

                    b.ToTable("TAiPermintaan", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TAiRespon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<decimal?>("BiayaEstimasi")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BiayaEstimasi");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid?>("DisetujuiOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DisetujuiOleh");

                    b.Property<Guid>("IdAiPermintaan")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdAiPermintaan");

                    b.Property<string>("JenisRespon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("JenisRespon");

                    b.Property<string>("ResponJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResponJson");

                    b.Property<string>("ResponRingkas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResponRingkas");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglDisetujui")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglDisetujui");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<int?>("TokenInput")
                        .HasColumnType("int")
                        .HasColumnName("TokenInput");

                    b.Property<int?>("TokenOutput")
                        .HasColumnType("int")
                        .HasColumnName("TokenOutput");

                    b.HasKey("Id");

                    b.ToTable("TAiRespon", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TChatCatatanInternal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid>("IdChatM")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdChatM");

                    b.Property<string>("IsiCatatan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IsiCatatan");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.HasKey("Id");

                    b.ToTable("TChatCatatanInternal", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TChatD", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("ArahPesan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ArahPesan");

                    b.Property<Guid?>("DibalasOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibalasOleh");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<bool>("DihasilkanOlehAi")
                        .HasColumnType("bit")
                        .HasColumnName("DihasilkanOlehAi");

                    b.Property<bool>("DikirimOlehCustomer")
                        .HasColumnType("bit")
                        .HasColumnName("DikirimOlehCustomer");

                    b.Property<Guid?>("IdAiRespon")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdAiRespon");

                    b.Property<Guid>("IdChatM")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdChatM");

                    b.Property<Guid?>("IdLogWebhookWaha")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdLogWebhookWaha");

                    b.Property<string>("IdPesanWaha")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("IdPesanWaha");

                    b.Property<string>("IsiPesan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IsiPesan");

                    b.Property<string>("JenisPesan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("JenisPesan");

                    b.Property<string>("NamaFileMedia")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NamaFileMedia");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<string>("PengirimNamaKontak")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("PengirimNamaKontak");

                    b.Property<string>("PengirimNomorWhatsapp")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("PengirimNomorWhatsapp");

                    b.Property<string>("PesanError")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PesanError");

                    b.Property<string>("StatusKirim")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("StatusKirim");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglDibaca")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglDibaca");

                    b.Property<DateTime?>("TglDikirim")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglDikirim");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<DateTime>("TglPesan")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglPesan");

                    b.Property<string>("TipeMime")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TipeMime");

                    b.Property<string>("UrlMedia")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("UrlMedia");

                    b.HasKey("Id");

                    b.HasIndex("IdPesanWaha");

                    b.ToTable("TChatD", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TChatM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("AiSudahMenyapa")
                        .HasColumnType("bit")
                        .HasColumnName("AiSudahMenyapa");

                    b.Property<bool>("AutoReplyAiAktif")
                        .HasColumnType("bit")
                        .HasColumnName("AutoReplyAiAktif");

                    b.Property<Guid?>("DiambilOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DiambilOleh");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid?>("DitugaskanKepada")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DitugaskanKepada");

                    b.Property<Guid?>("DitutupOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DitutupOleh");

                    b.Property<Guid?>("IdCustomer")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCustomer");

                    b.Property<Guid?>("IdGrupWhatsapp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdGrupWhatsapp");

                    b.Property<Guid?>("IdInstansi")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdInstansi");

                    b.Property<Guid?>("IdNomorWhatsapp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdNomorWhatsapp");

                    b.Property<Guid>("IdSesiWhatsapp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdSesiWhatsapp");

                    b.Property<Guid?>("IdStatusChat")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdStatusChat");

                    b.Property<string>("IdWahaTerdeteksi")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("IdWahaTerdeteksi");

                    b.Property<string>("JenisChat")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("JenisChat");

                    b.Property<int>("JumlahNotifikasiBelumTerbalas")
                        .HasColumnType("int")
                        .HasColumnName("JumlahNotifikasiBelumTerbalas");

                    b.Property<int>("JumlahPesanBelumDibaca")
                        .HasColumnType("int")
                        .HasColumnName("JumlahPesanBelumDibaca");

                    b.Property<string>("ModeAutoReplyAi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModeAutoReplyAi");

                    b.Property<string>("NamaGrupWhatsapp")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NamaGrupWhatsapp");

                    b.Property<string>("NamaKontak")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NamaKontak");

                    b.Property<string>("NomorWhatsapp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("NomorWhatsapp");

                    b.Property<string>("NomorWhatsappTerdeteksi")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("NomorWhatsappTerdeteksi");

                    b.Property<string>("Prioritas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Prioritas");

                    b.Property<string>("RingkasanAi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RingkasanAi");

                    b.Property<DateTime?>("TglAutoReplyAiTerakhir")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglAutoReplyAiTerakhir");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglChatTerakhir")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglChatTerakhir");

                    b.Property<DateTime?>("TglDiambil")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglDiambil");

                    b.Property<DateTime?>("TglDibalasTerakhir")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglDibalasTerakhir");

                    b.Property<DateTime?>("TglDitutup")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglDitutup");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<DateTime?>("TglFotoProfilDiambil")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglFotoProfilDiambil");

                    b.Property<DateTime?>("TglNotifikasiBelumTerbalasTerakhir")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglNotifikasiBelumTerbalasTerakhir");

                    b.Property<string>("UrlFotoProfil")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("UrlFotoProfil");

                    b.HasKey("Id");

                    b.ToTable("TChatM", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TChatPenugasan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("AlasanPenugasan")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("AlasanPenugasan");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid?>("DitugaskanDari")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DitugaskanDari");

                    b.Property<Guid>("DitugaskanKepada")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DitugaskanKepada");

                    b.Property<Guid>("IdChatM")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdChatM");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<DateTime>("TglPenugasan")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglPenugasan");

                    b.HasKey("Id");

                    b.ToTable("TChatPenugasan", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TLogAktivitas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Aksi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Aksi");

                    b.Property<string>("DataSebelumJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DataSebelumJson");

                    b.Property<string>("DataSesudahJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DataSesudahJson");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid?>("IdPengguna")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdPengguna");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IpAddress");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Keterangan");

                    b.Property<string>("Modul")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Modul");

                    b.Property<DateTime>("TglAktivitas")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglAktivitas");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("UserAgent");

                    b.HasKey("Id");

                    b.ToTable("TLogAktivitas", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TLogError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int?>("BarisError")
                        .HasColumnType("int")
                        .HasColumnName("BarisError");

                    b.Property<string>("ContextJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContextJson");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<string>("FileError")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("FileError");

                    b.Property<string>("LevelError")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LevelError");

                    b.Property<string>("PesanError")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PesanError");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StackTrace");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<DateTime>("TglError")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglError");

                    b.HasKey("Id");

                    b.ToTable("TLogError", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TLogIntegrasi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Berhasil")
                        .HasColumnType("bit")
                        .HasColumnName("Berhasil");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid?>("IdEndpointIntegrasi")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdEndpointIntegrasi");

                    b.Property<string>("KodeIntegrasi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("KodeIntegrasi");

                    b.Property<string>("MetodeHttp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MetodeHttp");

                    b.Property<string>("PesanError")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PesanError");

                    b.Property<string>("RequestJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RequestJson");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResponseJson");

                    b.Property<int?>("StatusHttp")
                        .HasColumnType("int")
                        .HasColumnName("StatusHttp");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<DateTime>("TglRequest")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglRequest");

                    b.Property<DateTime?>("TglResponse")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglResponse");

                    b.Property<string>("UrlEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("UrlEndpoint");

                    b.HasKey("Id");

                    b.ToTable("TLogIntegrasi", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TLogWebhookWaha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid?>("IdSesiWhatsapp")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdSesiWhatsapp");

                    b.Property<string>("JenisEvent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("JenisEvent");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<string>("PesanError")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PesanError");

                    b.Property<bool>("SudahDiproses")
                        .HasColumnType("bit")
                        .HasColumnName("SudahDiproses");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglDiproses")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglDiproses");

                    b.Property<DateTime>("TglDiterima")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglDiterima");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.HasKey("Id");

                    b.ToTable("TLogWebhookWaha", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TTicketD", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid?>("DitujukanKepada")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DitujukanKepada");

                    b.Property<Guid>("IdTicketM")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdTicketM");

                    b.Property<string>("IsiAktivitas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IsiAktivitas");

                    b.Property<string>("JenisAktivitas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("JenisAktivitas");

                    b.Property<string>("StatusSebelum")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StatusSebelum");

                    b.Property<string>("StatusSesudah")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StatusSesudah");

                    b.Property<DateTime>("TglAktivitas")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglAktivitas");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.HasKey("Id");

                    b.ToTable("TTicketD", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TTicketLampiran", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid>("IdTicketM")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdTicketM");

                    b.Property<string>("NamaFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NamaFile");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("PathFile");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<string>("TipeFile")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TipeFile");

                    b.Property<long?>("UkuranFile")
                        .HasColumnType("bigint")
                        .HasColumnName("UkuranFile");

                    b.HasKey("Id");

                    b.ToTable("TTicketLampiran", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TTicketM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("DeskripsiMasalah")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DeskripsiMasalah");

                    b.Property<Guid?>("DibuatDariPesanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatDariPesanId");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid?>("DitugaskanKepada")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DitugaskanKepada");

                    b.Property<Guid?>("DitutupOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DitutupOleh");

                    b.Property<Guid?>("IdChatM")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdChatM");

                    b.Property<Guid?>("IdCustomer")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCustomer");

                    b.Property<Guid?>("IdInstansi")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdInstansi");

                    b.Property<Guid?>("IdKategoriTicket")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdKategoriTicket");

                    b.Property<Guid?>("IdPrioritasTicket")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdPrioritasTicket");

                    b.Property<Guid?>("IdStatusTicket")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdStatusTicket");

                    b.Property<string>("JudulTicket")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("JudulTicket");

                    b.Property<string>("NomorTicket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NomorTicket");

                    b.Property<string>("RingkasanAi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RingkasanAi");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglDitugaskan")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglDitugaskan");

                    b.Property<DateTime?>("TglDitutup")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglDitutup");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<DateTime?>("TglSelesai")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglSelesai");

                    b.Property<DateTime?>("TglTargetSelesai")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglTargetSelesai");

                    b.HasKey("Id");

                    b.ToTable("TTicketM", (string)null);
                });

            modelBuilder.Entity("VPointCare.Web.Data.Entities.TTicketPenugasan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("AlasanPenugasan")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("AlasanPenugasan");

                    b.Property<Guid?>("DibuatOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DibuatOleh");

                    b.Property<Guid?>("DieditOleh")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DieditOleh");

                    b.Property<Guid?>("DitugaskanDari")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DitugaskanDari");

                    b.Property<Guid>("DitugaskanKepada")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DitugaskanKepada");

                    b.Property<Guid>("IdTicketM")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdTicketM");

                    b.Property<DateTime>("TglBuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglBuat");

                    b.Property<DateTime?>("TglEdit")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglEdit");

                    b.Property<DateTime>("TglPenugasan")
                        .HasColumnType("datetime2")
                        .HasColumnName("TglPenugasan");

                    b.HasKey("Id");

                    b.ToTable("TTicketPenugasan", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
